#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH


START_COMMAND="${OPENSHIFT_DATA_DIR}/sbt/bin/sbt run"
STOP_COMMAND1="kill $(ps -ef | grep 'sbt run' | grep -v grep | awk '{print $2}')"
STOP_COMMAND1="kill $(ps -ef | grep 'sbt gulpServe' | grep -v grep | awk '{print $2}')"


function is_running() {
  if [ ! -z "$(ps -ef | grep "$START_COMMAND" | grep -v grep)" ]; then
    return 0
  else
    return 1
  fi
}

  mkdir -p $OPENSHIFT_DATA_DIR/npmcache

  OLD_HOME=$HOME
  export HOME=$OPENSHIFT_DATA_DIR/npmcache

  cd "${OPENSHIFT_REPO_DIR}"
  ${OPENSHIFT_DATA_DIR}/sbt/bin/sbt compile
  ${OPENSHIFT_DATA_DIR}/sbt/bin/sbt npmInstall
  cd mforecast-web
  npm install --dev

  export HOME=$OLD_HOME
