#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH


START_COMMAND="${OPENSHIFT_DATA_DIR}/sbt/bin/sbt run"
STOP_COMMAND1="kill $(ps -ef | grep 'sbt run' | grep -v grep | awk '{print $2}')"
STOP_COMMAND1="kill $(ps -ef | grep 'sbt gulpServe' | grep -v grep | awk '{print $2}')"

function is_running() {
  if [ ! -z "$(ps -ef | grep "$START_COMMAND" | grep -v grep)" ]; then
    return 0
  else
    return 1
  fi
}

  if ! is_running; then
    client_result 'Application is already stopped.'
  else
    client_message 'Stopping application...'

    $STOP_COMMAND1 > /dev/null 2>&1
    $STOP_COMMAND2 > /dev/null 2>&1

    i=0
    while is_running && [ $i -lt 60 ]; do
      sleep 1
      i=$(($i + 1))
    done
    if is_running; then
      client_result 'Warning! Could not stop application!'
      exit 1
    else
      client_result 'Application stopped.'
    fi
  fi

